#pragma once
#include <chrono>
#include <cstddef>
#include <cstdint>
#include <concepts>
#include <functional>
#include <iterator>
#include <optional>
#include <type_traits>
#include <typeindex>
#include <utility>
#include "./stage_descriptor.hpp"
#include "./payload.hpp"
#include "./generator.hpp"

/**
 * @class StageBase
 * @brief Abstract base class for all pipeline stages.
 */
class StageBase {
      public:
	using CacheInvalidationFn = std::function<bool(
	        std::chrono::steady_clock::time_point,
	        std::chrono::steady_clock::time_point,
	        std::chrono::steady_clock::time_point,
	        uint64_t,
	        size_t)>;

	uint32_t  id = 0;
	StageType type_;
	uint32_t  requested_concurrency = 1;
	std::optional<uint32_t> cache_size_kb;
	std::chrono::milliseconds cache_ttl = std::chrono::minutes(5);
	std::optional<CacheInvalidationFn> cache_invalidation_fn;

	using InputType  = void;
	using OutputType = void;

	virtual ~StageBase() = default;

	virtual Payload execute(const Payload&) = 0;

	virtual std::optional<Payload> generate() {
		return std::nullopt;
	};

	virtual void consume(const Payload&) {};
};

template <typename T>
concept StageCompatible = std::is_base_of_v<StageBase, T>;

/**
 * @class SourceStage
 * @brief A pipeline stage that acts as a data generator (no inputs, only outputs).
 * @tparam Output The payload type generated by this stage.
 */
template <PayloadCompatible Output>
class SourceStage : public StageBase {
	generator<Output> generator_;

      public:
	using OutputType = Output;

	explicit SourceStage(generator<Output> generator) :
	        generator_(std::move(generator)) {
		type_ = StageType::SOURCE;
		PayloadRegistry::register_type<Output>();
	};

	Payload execute(const Payload&) override {
		return {};
	}

	std::optional<Payload> generate() override {
		auto item = generator_.next();
		if (!item.has_value()) {
			return std::nullopt;
		}
		return Payload(std::move(*item));
	}
};

/**
 * @class SinkStage
 * @brief A pipeline stage that acts as a data consumer (inputs, no outputs).
 * @tparam Input The payload type consumed by this stage.
 */
template <PayloadCompatible Input>
class SinkStage : public StageBase {
	std::function<void(const Input&)> consumer_fn_;

      public:
	using InputType = Input;

	explicit SinkStage(std::function<void(const Input&)> consumer_fn) :
	        consumer_fn_(consumer_fn) {
		type_ = StageType::SINK;
		PayloadRegistry::register_type<Input>();
	};

	Payload execute(const Payload&) override {
		return {};
	}

	void consume(const Payload& input_item) override {
		consumer_fn_(input_item.get<Input>());
	};
};

/**
 * @class FilterStage
 * @brief A standard 1-to-1 processing stage.
 * @tparam Input The payload type consumed by this stage.
 * @tparam Output The payload type produced by this stage.
 */
template <PayloadCompatible Input, PayloadCompatible Output>
class FilterStage : public StageBase {
	std::function<Output(const Input&)> processor_fn_;
	static constexpr uint32_t            default_cache_size_kb = 1024;
 	static constexpr std::chrono::milliseconds default_cache_ttl =
	        std::chrono::minutes(5);

      public:
	using InputType  = Input;
	using OutputType = Output;

	explicit FilterStage(std::function<Output(const Input&)> processor_fn) :
	        processor_fn_(processor_fn) {
		type_ = StageType::FILTER;
		PayloadRegistry::register_all<Input, Output>();
	};

	FilterStage& set_caching(
	        uint32_t size_kb = default_cache_size_kb,
	        std::chrono::milliseconds ttl = default_cache_ttl) {
		cache_size_kb = size_kb;
		cache_ttl     = ttl;
		return *this;
	}

	FilterStage& set_cache_invalidation(CacheInvalidationFn invalidation_fn) {
		cache_invalidation_fn = std::move(invalidation_fn);
		return *this;
	}

	Payload execute(const Payload& input_item) override {
		return processor_fn_(input_item.get<Input>());
	};
};

/**
 * @class FarmStage
 * @brief A concurrent processing stage that instances multiple workers.
 * @tparam Input The payload type consumed by this stage.
 * @tparam Output The payload type produced by this stage.
 */
template <PayloadCompatible Input, PayloadCompatible Output>
class FarmStage : public StageBase {
	std::function<Output(const Input&)> processor_fn_;
	static constexpr uint32_t            default_cache_size_kb = 1024;
	static constexpr std::chrono::milliseconds default_cache_ttl =
	        std::chrono::minutes(5);

      public:
	using InputType  = Input;
	using OutputType = Output;

	explicit FarmStage(std::function<Output(const Input&)> processor_fn) :
	        processor_fn_(processor_fn) {
		type_                 = StageType::FARM;
		requested_concurrency = 0;
		PayloadRegistry::register_all<Input, Output>();
	};

	FarmStage& concurrency(uint32_t concurrency) {
		requested_concurrency = concurrency;
		return *this;
	};

	FarmStage& set_caching(
	        uint32_t size_kb = default_cache_size_kb,
	        std::chrono::milliseconds ttl = default_cache_ttl) {
		cache_size_kb = size_kb;
		cache_ttl     = ttl;
		return *this;
	}

	FarmStage& set_cache_invalidation(CacheInvalidationFn invalidation_fn) {
		cache_invalidation_fn = std::move(invalidation_fn);
		return *this;
	}

	Payload execute(const Payload& input_item) override {
		return processor_fn_(input_item.get<Input>());
	};
};

template <typename T>
struct is_sink_stage : std::false_type {};

template <PayloadCompatible T>
struct is_sink_stage<SinkStage<T>> : std::true_type {};

template <typename T>
constexpr bool is_sink_stage_v = is_sink_stage<T>::value;

template <typename T>
struct is_source_stage : std::false_type {};

template <PayloadCompatible T>
struct is_source_stage<SourceStage<T>> : std::true_type {};

template <typename T>
constexpr bool is_source_stage_v = is_source_stage<T>::value;

template <typename T>
struct is_filter_stage : std::false_type {};

template <PayloadCompatible Input, PayloadCompatible Output>
struct is_filter_stage<FilterStage<Input, Output>> : std::true_type {};

template <typename T>
constexpr bool is_filter_stage_v = is_filter_stage<T>::value;

template <typename T>
struct is_farm_stage : std::false_type {};

template <PayloadCompatible Input, PayloadCompatible Output>
struct is_farm_stage<FarmStage<Input, Output>> : std::true_type {};

template <typename T>
constexpr bool is_farm_stage_v = is_farm_stage<T>::value;
